# Generated by Django 5.0.6 on 2024-06-05 11:20

import datetime
import inventory_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_avaliable', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory_app.models.upload_to)),
                ('QR_CODE', models.ImageField(blank=True, null=True, upload_to='qrcodes')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 11, 20, 7, 280569, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 11, 20, 7, 280585, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
